# Generated by Django 3.1.6 on 2021-04-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklibrary', '0002_auto_20210318_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='number_in_series',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
