# Generated by Django 3.1.6 on 2021-04-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklibrary', '0003_series_number_in_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='number_in_series',
        ),
        migrations.AddField(
            model_name='book',
            name='number_in_series',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
