# Generated by Django 3.1.6 on 2021-04-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklibrary', '0005_auto_20210410_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='un_owned',
            field=models.BooleanField(default=True),
        ),
    ]
