# Generated by Django 3.2.4 on 2021-06-18 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklibrary', '0006_datesung_people_publisher_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='arrangers',
            field=models.ManyToManyField(blank=True, related_name='songs_arranged', to='booklibrary.People'),
        ),
        migrations.AlterField(
            model_name='song',
            name='composers',
            field=models.ManyToManyField(blank=True, related_name='songs_composed', to='booklibrary.People'),
        ),
        migrations.AlterField(
            model_name='song',
            name='lyricists',
            field=models.ManyToManyField(blank=True, related_name='songs_lirisized', to='booklibrary.People'),
        ),
    ]
