# Generated by Django 3.1.6 on 2021-04-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklibrary', '0006_book_un_owned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='un_owned',
            field=models.BooleanField(default=False),
        ),
    ]
