# Generated by Django 3.1.5 on 2021-05-14 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklibrary', '0006_arranger_composer_datesung_lyracist_publisher_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='notes',
            field=models.CharField(blank=True, max_length=5000, null=True),
        )
    ]
