# Generated by Django 3.1.5 on 2021-05-14 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booklibrary', '0007_auto_20210513_2208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='composer',
            new_name='composers',
        ),
        migrations.AlterField(
            model_name='song',
            name='arranger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='songs', to='booklibrary.composer'),
        ),
        migrations.DeleteModel(
            name='Arranger',
        ),
    ]
