# Generated by Django 3.2.4 on 2021-06-25 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklibrary', '0007_auto_20210617_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='datesung',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200)),
                ('songs', models.ManyToManyField(related_name='tags', to='booklibrary.Song')),
            ],
        ),
    ]
