# Generated by Django 3.2.3 on 2021-07-15 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booklibrary', '0009_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='songs', to='booklibrary.collection'),
        ),
    ]
